name                = OpenSearch-Client
author              = Mark Dootson <mdootson@cpan.org>
license             = Apache_2_0
copyright_holder    = Mark Dootson
version             = 3.007001

[GatherDir / lib]
root                = ../source-main/lib
prefix              = lib

[GatherDir / t]
root                = ../source-main/t
prefix              = t

[GatherFile / notice]
root                = ../source-main
filename            = NOTICE

[GatherFile / license]
root                = ../source-main
filename            = LICENSE

[GatherFile / changes]
root                = ../source-main
filename            = Changes

[MetaResources]
homepage          = https://metacpan.org/pod/OpenSearch::Client
bugtracker.web    = https://github.com/markdootson/opensearch-client-perl/issues
repository.url    = git://github.com/markdootson/opensearch-client-perl.git
repository.web    = https://github.com/markdootson/opensearch-client-perl
repository.type   = git

[MakeMaker]

[MetaJSON]

[Manifest]

; [GithubMeta]
; issues = 1

[CPANFile]
;[CopyFilesFromBuild]
;copy = cpanfile
;copy = META.json

; [VersionFromModule]

[AutoPrereqs]
skip = ^OpenSearch::Client::
skip = Mojo::UserAgent
skip = JSON::XS
skip = Cpanel::JSON::XS

[Prereqs]
IO::Socket                          = 0

[Prereqs / TestRequires]
base                                = 2.18
Test::More                          = 0.98
Test::EOL                           = 0
Test::NoTabs                        = 0
TAP::Harness::JUnit                 = 0
YAML                                = 0
YAML::XS                            = 0

[Prereqs / Recommends]
URI::Escape::XS                     = 0

[Prereqs / TestRecommends]
Cpanel::JSON::XS                    = 0
JSON::XS                            = 2.26
Mojo::UserAgent                     = 0
Mojo::IOLoop                        = 0

